
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class KPI_Dept
{

    public int AutoID { get; set; }

    public string Dept_Name { get; set; }

    public string Dept_Mgr { get; set; }

    public string Dept_Mgr_Email { get; set; }

    public Nullable<int> Dept_Mgr_EmpID { get; set; }

}

}
