
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Project_Charter
{

    public int TQMID { get; set; }

    public string Business_Case { get; set; }

    public string Opportunity { get; set; }

    public string Risk_Assessment { get; set; }

    public Nullable<int> Goal { get; set; }

    public Nullable<int> Scope { get; set; }

    public Nullable<int> Project_Plan { get; set; }

    public Nullable<int> MethodologyID { get; set; }

    public Nullable<int> CurrentStep { get; set; }

}

}
