

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TQMEntitiesModel : DbContext
{
    public TQMEntitiesModel()
        : base("name=TQMEntitiesModel")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Dept_Info> Dept_Info { get; set; }

    public virtual DbSet<KPI> KPIs { get; set; }

    public virtual DbSet<KPI_Dept> KPI_Dept { get; set; }

    public virtual DbSet<Project_Charter> Project_Charter { get; set; }

    public virtual DbSet<TQM_Approval> TQM_Approval { get; set; }

    public virtual DbSet<TQM_Details> TQM_Details { get; set; }

    public virtual DbSet<TQM_Member> TQM_Member { get; set; }

    public virtual DbSet<TQM_Methodology> TQM_Methodology { get; set; }

    public virtual DbSet<TQM_MethodologyStep> TQM_MethodologyStep { get; set; }

    public virtual DbSet<TQM_Officials> TQM_Officials { get; set; }

    public virtual DbSet<TQM_Project_Plan> TQM_Project_Plan { get; set; }

    public virtual DbSet<TQM_Role> TQM_Role { get; set; }

    public virtual DbSet<TQM_Status_List> TQM_Status_List { get; set; }

    public virtual DbSet<TQM_UploadCompletedStory> TQM_UploadCompletedStory { get; set; }

}

}

