
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TQM_Details
{

    public int AutoID { get; set; }

    public int SerialNo { get; set; }

    public Nullable<int> EmpNo { get; set; }

    public string EmpName { get; set; }

    public string Dept { get; set; }

    public string Idea { get; set; }

    public Nullable<int> KPI_Dept { get; set; }

    public string KPI { get; set; }

    public string SynergyModel { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> TransactDate { get; set; }

}

}
