
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TQM_Status_List
{

    public int AutoID { get; set; }

    public int StatusNo { get; set; }

    public string Description { get; set; }

}

}
