
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TQM_MethodologyStep
{

    public int AutoID { get; set; }

    public int MethodologyID { get; set; }

    public string StepName { get; set; }

    public string StepDescription { get; set; }

    public Nullable<int> StepNumber { get; set; }

    public Nullable<bool> RequireApproval { get; set; }

    public Nullable<int> ApprovalRoleID { get; set; }

}

}
