
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TQMPG.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TQM_Officials
{

    public int AutoID { get; set; }

    public Nullable<int> EmpNo { get; set; }

    public string EmpName { get; set; }

    public string EmpEmail { get; set; }

    public Nullable<int> RoleID { get; set; }

}

}
