//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQMPG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_eLeave_EmployeeDetails
    {
        public string empEmployeeNo { get; set; }
        public string empFullName { get; set; }
        public string preDeptDesc { get; set; }
        public string empEmail { get; set; }
        public string PreSectionDesc { get; set; }
        public string preJobFunctionDesc { get; set; }
        public string empCalCode { get; set; }
        public Nullable<bool> empSupervisor { get; set; }
        public string empDirectSupNo { get; set; }
        public string supName { get; set; }
        public string supEmail { get; set; }
        public string indName { get; set; }
        public string indEmail { get; set; }
        public string preJobCat { get; set; }
        public string prePostDesc { get; set; }
        public string empBadgeNo { get; set; }
    }
}
